name: "Rust Cache"
description: "A GitHub Action that implements smart caching for rust/cargo projects with sensible defaults."
author: "Arpad Borsos <swatinem@swatinem.de>"
inputs:
  key:
    description: "An additional key for the cache"
    required: false
  sharedKey:
    description: "An additional cache key that is stable over multiple jobs"
    required: false
  envVars:
    description: "Additional environment variables to include in the cache key, separeted by spaces"
    required: false
  workspaces:
    description: "Paths to multiple Cargo workspaces and their target directories, separated by newlines"
    required: false
  cache-on-failure:
    description: "Cache even if the build fails. Defaults to false"
    required: false
outputs:
  cache-hit:
    description: "A boolean value that indicates an exact match was found"
runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: "success() || env.CACHE_ON_FAILURE == 'true'"
branding:
  icon: "archive"
  color: "gray-dark"
