name: install

on: [push, pull_request]

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo install` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v2

      - run: rustup toolchain install stable --profile minimal

      - uses: ./

      - run: cargo install cargo-deny --locked
